### ISSUE TITLE
running "php composer.phar install" failed,

### ISSUE THREAD

**Issue by luckypoem** [inouire/mini-net#5]
hi.

as3:~/mini-net# curl -s http://getcomposer.org/installer | php
# !/usr/bin/env php

All settings correct for using Composer
Downloading...
Composer successfully installed to: /root/mini-net/composer.phar
Use it: php composer.phar
as3:~/mini-net# ls
app  composer.json  composer.phar  src        web
bin  composer.lock  README.md      update.sh
as3:~/mini-net# php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for symfony/icu v1.2.1 -> satisfiable by symfony/icu[v1.2.1].
    - symfony/icu v1.2.1 requires lib-icu >=4.4 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
  Problem 2
    - symfony/icu v1.2.1 requires lib-icu >=4.4 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - symfony/symfony v2.3.12 requires symfony/icu ~1.0 -> satisfiable by symfony/icu[v1.2.1].
    - Installation request for symfony/symfony v2.3.12 -> satisfiable by symfony/symfony[v2.3.12].
as3:~/mini-net#

how to fix it?
tks!

**Comment by inouire** [comment]
Hello,

The problem comes from an incompatibilty about the intl component.
Did you install php5-intl package on your server ?
If it's the case, you can have a look at this, there is a dedicated section that should help you:
http://symfony.com/doc/current/components/intl.html
